# Generated by Django 6.0.1 on 2026-01-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevels',
            name='stockLev',
            field=models.IntegerField(default=0),
        ),
    ]
