# Generated by Django 6.0.1 on 2026-01-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_stocklevels_stocklev'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklevels',
            name='company',
            field=models.CharField(default='xxxxxxxxxx', max_length=10),
        ),
        migrations.AddField(
            model_name='stocklevels',
            name='excludeFSF',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocklevels',
            name='groupDesc',
            field=models.CharField(default='xxxxxxxxxx', max_length=100),
        ),
        migrations.AddField(
            model_name='stocklevels',
            name='inActive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stocklevels',
            name='rangeName',
            field=models.CharField(default='xxxxxxxxxx', max_length=100),
        ),
        migrations.AddField(
            model_name='stocklevels',
            name='subGroupDesc',
            field=models.CharField(default='xxxxxxxxxx', max_length=100),
        ),
        migrations.AlterField(
            model_name='stocklevels',
            name='partDesc',
            field=models.CharField(default='xxxxxxxxxx', max_length=150),
        ),
        migrations.AlterField(
            model_name='stocklevels',
            name='partNum',
            field=models.CharField(default='xxxxxxxxxxx', max_length=11),
        ),
    ]
