# Generated by Django 6.0.1 on 2026-01-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_stocklevels_company_stocklevels_excludefsf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupDescView',
            fields=[
                ('groupDesc', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'groupDescView',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SubGroupDescView',
            fields=[
                ('subGroupDesc', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'subGroupDescView',
                'managed': False,
            },
        ),
    ]
