# Generated by Django 6.0.1 on 2026-01-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_groupdescview_subgroupdescview'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeNameView',
            fields=[
                ('rangeName', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'rangeNameView',
                'managed': False,
            },
        ),
    ]
