# Generated by Django 6.0.1 on 2026-02-01 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custID',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
