# Generated by Django 6.0.1 on 2026-02-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_userprofile_custid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='custID',
            new_name='cust_ID',
        ),
    ]
