# Generated by Django 6.0.1 on 2026-02-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_custid_userprofile_cust_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
