# Generated by Django 6.0.1 on 2026-02-01 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_userprofile_website_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='website_address',
            new_name='website',
        ),
    ]
