# Generated by Django 6.0.1 on 2026-02-06 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_website_address_userprofile_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_ID',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
