# Generated by Django 6.0.1 on 2026-02-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_userprofile_company_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklevels',
            name='excludeFSF',
        ),
    ]
