# Generated by Django 6.0.1 on 2026-02-06 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_stocklevels_excludefsf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocklevels',
            name='inActive',
        ),
    ]
