# Generated by Django 6.0.1 on 2026-02-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='company_Name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
