# Generated by Django 6.0.1 on 2026-03-01 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_userprofile_company_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocklevels',
            options={'verbose_name': 'Stock Level', 'verbose_name_plural': 'Stock Levels'},
        ),
        migrations.AlterModelTable(
            name='stocklevels',
            table='api_stocklevels',
        ),
    ]
